spring:
  cloud:
    consul:
      host: ${hostname.consul}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        prefer-ip-address: true




hostname:
  consul: consul
