spring:
  profiles:
    active: dev
  application:
    name: service-user
  cloud:
      consul:
        discovery:
          service-name: service-user




server:
  port: 8763


logging:
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    health:
      show-details: always

