spring:
  cloud:
    consul:
      host: ${hostname.consul}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${hostname.mysql}:3306/user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
   # JPA 相关配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: create



hostname:
  mysql: localhost
  redis: localhost
  consul: localhost
  zipkin: localhost

